/**
 * GENERATED by scripts/apply-dsh-ui-fixes.sh — do not edit by hand.
 * The version and path of the harness install this bundle was built against,
 * used by the sidebar badge until the host route /plugin/hawk-hq/version is
 * live (it answers on the next harness boot). Re-run the script after every
 * harness upgrade; see README.md.
 *
 * The values below are the placeholders this repo ships: run the script once
 * (it is step 3 of the install in the root README) to bake in your own install.
 * With an empty stamp the tooltip simply omits the "bundle built" line, and the
 * badge shows the version the host route reports.
 */
export const DSH_VERSION_AT_BUILD = 'unknown'
export const DSH_INSTALL_AT_BUILD = ''
export const DSH_BUILD_STAMP = ''
