#!/usr/bin/env bash
# apply-dsh-ui-fixes.sh — bring the UI customizations back after any harness
# install or upgrade, and keep the version badge telling the truth.
#
# What it does, in order:
#   1. resolves the harness install that `dsh` on PATH points at and reads its
#      version, aborting if that fails (never guess a version);
#   2. regenerates src/client/dsh-build.ts with that version + a timestamp, so
#      the browser half always knows which harness it is looking at;
#   3. grows the `sidebar.version` seat in the installed ui-sidebar bundle
#      (scripts/patch_sidebar_seat.py — idempotent, verified, revertible);
#   4. rebuilds the browser half (tsdown) so the badge ships the freshly read
#      version;
#   5. reports what the harness web server actually serves, when it is reachable.
#
# Run it after every `npm i -g @deepseek-ai/dsh@…`. Nothing here needs a harness
# restart: client bundles are served from disk with `no-cache`, so a browser
# refresh picks the result up — use a HARD reload, since a plain reload can still
# render the previous build. The host route `/plugin/hawk-hq/version` only comes
# alive on the next harness boot.
#
#   <repo>/plugins/dsh-client-ui-hawk-hq/scripts/apply-dsh-ui-fixes.sh
#
# Environment overrides: DSH_WEB_URL (default http://127.0.0.1:3081),
# DSH_SERVICE (systemd user unit, default dsh-web — used only to read the
# launch-token URL out of the journal).
set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEB_URL="${DSH_WEB_URL:-http://127.0.0.1:3081}"
SERVICE="${DSH_SERVICE:-dsh-web}"

say() { printf 'apply-dsh-ui-fixes: %s\n' "$*"; }
die() { printf 'apply-dsh-ui-fixes: ERROR: %s\n' "$*" >&2; exit 1; }

# 1. The install `dsh` points at — the same one the web server runs.
DSH_BIN="$(command -v dsh || true)"
[ -n "$DSH_BIN" ] || die 'no `dsh` on PATH'
DSH_ENTRY="$(readlink -f "$DSH_BIN")"           # …/@deepseek-ai/dsh/lib/bin.js
DSH_ROOT="$(dirname "$(dirname "$DSH_ENTRY")")" # …/@deepseek-ai/dsh
PKG_JSON="$DSH_ROOT/package.json"
[ -f "$PKG_JSON" ] || die "no package.json at $PKG_JSON"
DSH_VERSION="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); assert d.get("name")=="@deepseek-ai/dsh", d.get("name"); print(d["version"])' "$PKG_JSON")" \
  || die "cannot read the harness version from $PKG_JSON"
say "harness install: $DSH_ROOT (version $DSH_VERSION)"

# 2. Bake it into the browser half.
BUILD_FILE="$PLUGIN_DIR/src/client/dsh-build.ts"
STAMP="$(date -Iseconds)"
cat > "$BUILD_FILE" <<EOF
/**
 * GENERATED by scripts/apply-dsh-ui-fixes.sh — do not edit by hand.
 * The version and path of the harness install this bundle was built against,
 * used by the sidebar badge until the host route /plugin/hawk-hq/version is
 * live (it answers on the next harness boot). Re-run the script after every
 * harness upgrade; see README.md.
 */
export const DSH_VERSION_AT_BUILD = '$DSH_VERSION'
export const DSH_INSTALL_AT_BUILD = '$DSH_ROOT'
export const DSH_BUILD_STAMP = '$STAMP'
EOF
say "baked $DSH_VERSION into src/client/dsh-build.ts"

# 3. The sidebar seat.
python3 "$PLUGIN_DIR/scripts/patch_sidebar_seat.py"

# 4. Rebuild (tsdown emits lib/client.js + lib/index.js).
cd "$PLUGIN_DIR"
if [ -x node_modules/.bin/tsdown ]; then
  ./node_modules/.bin/tsdown >/dev/null || die 'tsdown build failed'
else
  die 'tsdown is not installed in the plugin (node_modules/.bin/tsdown missing) — run pnpm install'
fi
say 'rebuilt lib/client.js and lib/index.js'

# 5. Report what the harness actually serves (skipped when it is not running).
# A missing live check is a WARNING, never a failure: everything above already
# succeeded, and the serving shape is upstream's business. 0.1.5+ serves all
# client code as one combo bundle (/plugins/??a/client.js,b/client.js&rev=…), so
# the per-plugin paths 404 there — check the combo when it exists, the old paths
# otherwise.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
touch "$TMP/cookies"
TOKEN="$(journalctl --user -u "$SERVICE" --no-pager 2>/dev/null | grep -oP 'dsh web: http\S*[?&]token=\K\S+' | tail -1 || true)"
[ -n "${TOKEN:-}" ] && curl -fsS -c "$TMP/cookies" -o /dev/null --max-time 4 "$WEB_URL/?token=$TOKEN" 2>/dev/null || true

if curl -fsS -b "$TMP/cookies" -o "$TMP/index.html" --max-time 4 "$WEB_URL/" 2>/dev/null; then
  BUNDLES="$TMP/bundles.js"
  : >"$BUNDLES"
  COMBO="$(grep -oP 'href="\K/plugins/\?\?[^"]+' "$TMP/index.html" | head -1 | sed 's/&amp;/\&/g' || true)"
  if [ -n "$COMBO" ]; then
    curl -fsS -b "$TMP/cookies" --max-time 30 "$WEB_URL$COMBO" >>"$BUNDLES" 2>/dev/null || true
  else
    for path in "dsh-client-ui-hawk-hq/client.js" "@deepseek-ai/dsh-client-ui-sidebar/client.js"; do
      curl -fsS -b "$TMP/cookies" --max-time 15 "$WEB_URL/plugins/$path" >>"$BUNDLES" 2>/dev/null || true
    done
  fi
  if [ -s "$BUNDLES" ]; then
    seat="$(grep -c '"sidebar.version"' "$BUNDLES" || true)"
    badge="$(grep -c 'hhq-ver' "$BUNDLES" || true)"
    if [ "${seat:-0}" -ge 1 ] && [ "${badge:-0}" -ge 1 ]; then
      say "verified live: sidebar seat present, badge present — hard-reload the browser"
    else
      say "WARNING: the served bundle has no seat ($seat) or no badge ($badge) yet — a harness restart, or the next boot's ExecStartPre, may be needed"
    fi
    if curl -fsS -b "$TMP/cookies" -o /dev/null --max-time 5 "$WEB_URL/plugin/hawk-hq/version" 2>/dev/null; then
      say 'host route /plugin/hawk-hq/version is live'
    else
      say 'host route /plugin/hawk-hq/version is not live yet (comes up on the next harness boot; the badge reads the registry from the browser until then)'
    fi
  else
    say 'WARNING: could not fetch the served client bundle(s) — skipped the live check'
  fi
else
  say "harness web server not reachable at $WEB_URL — skipped the live check"
fi

say "done: DSH $DSH_VERSION"
